/* eslint-disable @typescript-eslint/ban-ts-comment */
/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react"
// biome-ignore lint/suspicious/noExplicitAny: autogenerated file
export const Index: Record<string, any> = {
  "index": {
    name: "index",
    type: "registry:style",
    registryDependencies: ["utils"],
    files: [],
    component: null,
  },
  "style": {
    name: "style",
    type: "registry:style",
    registryDependencies: ["utils"],
    files: [],
    component: null,
  },
  "button": {
    name: "button",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "src/registry/new-york-v4/ui/button.tsx",
      type: "registry:ui"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/ui/button.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "card": {
    name: "card",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "src/registry/new-york-v4/ui/card.tsx",
      type: "registry:ui"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/ui/card.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "badge": {
    name: "badge",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "src/registry/new-york-v4/ui/badge.tsx",
      type: "registry:ui"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/ui/badge.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "project-card": {
    name: "project-card",
    type: "registry:component",
    registryDependencies: ["card","badge","button"],
    files: [{
      path: "src/registry/new-york-v4/components/project-card.tsx",
      type: "registry:component"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/components/project-card.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "hero-section": {
    name: "hero-section",
    type: "registry:block",
    registryDependencies: ["button"],
    files: [{
      path: "src/registry/new-york-v4/blocks/hero-section.tsx",
      type: "registry:component"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/blocks/hero-section.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "use-mobile": {
    name: "use-mobile",
    type: "registry:hook",
    registryDependencies: undefined,
    files: [{
      path: "src/registry/new-york-v4/hooks/use-mobile.ts",
      type: "registry:hook"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/hooks/use-mobile.ts")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "use-toggle": {
    name: "use-toggle",
    type: "registry:hook",
    registryDependencies: undefined,
    files: [{
      path: "src/registry/new-york-v4/hooks/use-toggle.ts",
      type: "registry:hook"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/hooks/use-toggle.ts")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "use-media-query": {
    name: "use-media-query",
    type: "registry:hook",
    registryDependencies: undefined,
    files: [{
      path: "src/registry/new-york-v4/hooks/use-media-query.ts",
      type: "registry:hook"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/hooks/use-media-query.ts")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "use-local-storage": {
    name: "use-local-storage",
    type: "registry:hook",
    registryDependencies: undefined,
    files: [{
      path: "src/registry/new-york-v4/hooks/use-local-storage.ts",
      type: "registry:hook"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/hooks/use-local-storage.ts")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "format-date": {
    name: "format-date",
    type: "registry:lib",
    registryDependencies: undefined,
    files: [{
      path: "src/registry/new-york-v4/lib/format-date.ts",
      type: "registry:lib"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/lib/format-date.ts")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "validate-email": {
    name: "validate-email",
    type: "registry:lib",
    registryDependencies: undefined,
    files: [{
      path: "src/registry/new-york-v4/lib/validate-email.ts",
      type: "registry:lib"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/lib/validate-email.ts")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "button-demo": {
    name: "button-demo",
    type: "registry:example",
    registryDependencies: ["button"],
    files: [{
      path: "src/registry/new-york-v4/examples/button-demo.tsx",
      type: "registry:example"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/examples/button-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "card-demo": {
    name: "card-demo",
    type: "registry:example",
    registryDependencies: ["card","button"],
    files: [{
      path: "src/registry/new-york-v4/examples/card-demo.tsx",
      type: "registry:example"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/examples/card-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "project-card-demo": {
    name: "project-card-demo",
    type: "registry:example",
    registryDependencies: ["project-card"],
    files: [{
      path: "src/registry/new-york-v4/examples/project-card-demo.tsx",
      type: "registry:example"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/examples/project-card-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  }